### ISSUE TITLE
git ship: configure to merge instead of squash-merge

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#672] opened 2015-09-29 17:35 UTC
The screencast mentions this ability

**Comment by kevgo** [comment] 2015-10-19 20:55
Ideally this functionality would include a squash into a single commit before merging. Since this has side effects, I guess this needs to be enabled by a configuration setting.

**Comment by kevgo** [comment] 2015-11-26 16:42
Duplicate of #673, closing this one.

**Closed by kevgo** 2015-11-26 16:42 UTC
