### ISSUE TITLE
git town prune

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#1102] opened 2018-02-02 13:23 UTC
> When having used Git Town for a while
I want to be able to clean up the documentation
So that my Git configuration isn’t littered with outdated entries. 

- running “git town config prune” deletes all Git Town configuration
  for branches that don’t exist in the local workspace

**Comment by kevgo** [comment] 2018-02-02 13:29
Maybe merge this with “git town prune-branches”

**Comment by charlierudolph** [comment] 2018-02-06 02:56
this is a duplicate of #777

**Closed** 2018-04-05 21:40 UTC
