### ISSUE TITLE
Add feature spec for tags that are not attached to pulled commits

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#492] opened 2015-04-15 14:37 UTC
@charlierudolph commented in #461:

> So tags are automatically pulled if they are attached to commits you normally pull (ie: a commit on a branch). But if the tag is not on a commit that gets pulled down (ie: a commit that is not on a branch), then it would not get the tag. [...] (the current) feature test is not sufficient.

**Comment by kevgo** [comment] 2015-04-15 14:49
Assuming that I only want to see tags for branches that I have checked out on my machine, and `git sync --all` pulls down all commits for all my local branches, wouldn't the current behavior pull down all the tags that I want/need?

**Comment by kevgo** [comment] 2015-04-15 14:51
Starting with [Git 1.9](https://github.com/git/git/blob/d7aced95cd681b761468635f8d2a8b82d7ed26fd/Documentation/RelNotes/1.9.txt#L18-L20), Git fetches all commits and tags when run with `git fetch --tags`. The problem is that older Linux distros, like the one on CircleCI, still run on Git 1.8, so we can't rely on this feature yet.

**Comment by kevgo** [comment] 2015-04-15 14:57
From http://stackoverflow.com/questions/1204190/does-git-fetch-tags-include-git-fetch it seems as 
`git fetch origin 'refs/heads/*:refs/remotes/origin/*' '+refs/tags/*:refs/tags/*'` should pull all commits and all tags at the same time.

**Comment by charlierudolph** [comment] 2015-04-15 15:13
How about having separate behavior based on the version of git running? That way its easy to just remove support for Git 1.8 later when its use is low enough.

**Comment by charlierudolph** [comment] 2015-04-15 15:27
I think all we need is
```
# Git < 1.9
git fetch
git fetch --tags

# Git >= 1.9
git fetch --tags
```
[Git 1.9 release notes](https://github.com/git/git/blob/d7aced95cd681b761468635f8d2a8b82d7ed26fd/Documentation/RelNotes/1.9.txt#L18-L20)

**Comment by kevgo** [comment] 2015-04-15 15:58
That would be super easy to implement, but I haven't figured out a way to test that.

**Comment by charlierudolph** [comment] 2015-07-25 18:03
Closing as duplicate of #429

**Closed by charlierudolph** 2015-07-25 18:03 UTC
Labels: improvement
