### ISSUE TITLE
git-town doesn't resume properly when the network fails

### ISSUE THREAD

**Issue by Bowbaq** [Originate/git-town#942] opened 2017-05-26 08:40 UTC
## Steps
1. `git hack test-branch`
2. add some commits
3. `git ship`, interrupt the network while pushing

## Expected
`git-town` detects the failure and resumes normally on the next invocation

## Actual
`git-town` appears to consider the `git push` phase done and deletes the branch on the remote  and locally instead

I have the output available if needed

**Comment by kevgo** [comment] 2017-05-26 13:57
Thanks for the bug report, @Bowbaq! Interesting edge case! I think Git Town can handle this situation even better: 

- detect the failed operation, stop, print a useful error message
- the user can try to fix their internet connection
- once done, the user can run `git ship --continue` or `git ship --abort` to finish what they started, or abort safely
- if the connection remains flaky, the user can keep trying until it goes through

What do you think?

Also, since this is hard to reproduce, please post the output you got on your machine.

**Comment by charlierudolph** [comment] 2017-08-16 05:46
@Bowbaq what version were you using? I don't expect this to happen with v4 or after but do think it would happen with v3 and below

**Comment by kevgo** [comment] 2019-01-25 05:12
Closing as obsolete

**Closed by kevgo** 2019-01-25 05:12 UTC
