### ISSUE TITLE
hack-push-flag defaults to 'false'

### ISSUE THREAD

**Issue by kelbyers** [Originate/git-town#970] opened 2017-06-26 15:46 UTC
The documentation states that hack-push-flag defaults to 'true', but for me, it is defaulting to 'false'. I would not care so much, but there is no global way to change the default configuration for that (at least as also stated in the documentation, that the setting for this is on a per-repo basis). Thus, I have to set it on every repo I have, because I want it to always be 'true' for my usage.

```
$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = URL
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master

$ git town hack-push-flag
false
```

**Comment by charlierudolph** [comment] 2017-06-26 17:48
Where in the documentation does it say that? We did recently switch the default to false. Any chance you could create a PR updating the documentation?

**Comment by kevgo** [comment] 2017-06-26 18:36
@kelbyers @charlierudolph the documentation when running provided by the binary mentioned the old `true` default value. I have created #971 to fix this. 

@kelbyers Git provides a global configuration file that we could use here. Git Town does not officially support the global Git config yet, since nobody has requested this feature so far. If you want to experiment to get this working on your machine, run this on the command line:

```
git config --add --global git-town.hack-push-flag true
```

This should (in theory) set the `hack-push-flag` option to `true` for all your repos.
To remove the setting:

```
git config --unset --global git-town.hack-push-flag
```

It's pretty risk free, since it does not interfere with normal Git, and you can delete the global setting at any time. Please let us know if that worked.

**Comment by kelbyers** [comment] 2017-06-26 19:51
@charlierudolph @kevgo my mention of `true` being the default value comes from the main README.md.

I'll git the global config setting a try and let you know how it works for me.

**Comment by kevgo** [comment] 2017-06-26 19:56
@kelbyers thanks for the pointer, I have added a fix for that to my PR

**Comment by kelbyers** [comment] 2017-06-26 20:01
well, setting the value in the global config does not seem to be picked up

```
$ git config --add --global git-town.hack-push-flag true

$ tail -2 ~/.gitconfig
[git-town]
	hack-push-flag = true

$ git town hack-push-flag
false

$ grep -e town -e hack .git/config

$
```

**Comment by kevgo** [comment] 2017-06-26 20:20
What happens when you run `git config --get-regexp 'git-town'` in your repo? It should correctly pick up the global config and display `git-town.hack-push-flag true` (amongst other things).

**Comment by kevgo** [comment] 2017-06-27 14:22
I have shipped #971, the fixes to the documentation within the tool will go out with the next release. The last thing to resolve here is whether we can use the global Git configuration for things like the hack-push flag. @kelbyers did you get a chance to run `git config --get-regexp 'git-town'` in your repo?

**Comment by kevgo** [comment] 2017-07-31 12:09
@kelbyers confirmed that it doesn't work right now, because Git Town currently only looks at the local Git configuration. The good news is that once #978 ships, this issue should work as well, since Git Town then officially supports the global Git configuration.

**Comment by kevgo** [comment] 2017-08-16 06:47
Closing because version 4.2.0 supports global Git configuration. Please reopen if the issue still exists.

**Comment by charlierudolph** [comment] 2017-08-16 16:06
@kevgo looking at the current code, its doesn't appear to look at the global config for the hack push flag. https://github.com/Originate/git-town/blob/v4.2.0/src/git/config.go#L250

**Comment by kelbyers** [comment] 2017-08-23 21:51
@kevgo sorry about not responding earlier. I have git-town 4.2.1 installed, and it still does not honor the global value of the flag.

```
$ git config --get-regexp 'git-town'
git-town.hack-push-flag true
$ git hack 259-tag_dates

[master] git fetch --prune

[master] git rebase origin/master
Current branch master is up to date.

[master] git checkout -b 259-tag_dates master
Switched to a new branch '259-tag_dates'
$ gr show origin
* remote origin
  Fetch URL: git@github.homedepot.com:ose-automation-puppet/puppet-ci.git
  Push  URL: git@github.homedepot.com:ose-automation-puppet/puppet-ci.git
  HEAD branch: master
  Remote branches:
    feature-jenkins tracked
    feature-thdlib  tracked
    master          tracked
    savemodname     tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

**Closed** 2017-12-20 15:25 UTC
