### ISSUE TITLE
Git ship not closing PR's on github

### ISSUE THREAD

**Issue by a-morales** [Originate/git-town#961] opened 2017-06-05 18:47 UTC
Scenario: Feature branches with appends closes properly
  When I create a new feature branch "parent"
  And I create a pull request for the feature branch "parent"
  And I append from the feature branch "parent" as "child"
  When I ship the feature branch "parent"
  Then I expect the feature branch "parent" to be closed on github.

Actual: "parent" pull request stays open on github.

**Comment by charlierudolph** [comment] 2017-06-05 18:56
Going to close this as a duplicate of #750.

For now, you can add `closes #<pr_number>` to commit message for it to the link the commit to the PR and automatically close the PR

**Closed by charlierudolph** 2017-06-05 18:56 UTC
