### ISSUE TITLE
Deb packages missing

### ISSUE THREAD

**Issue by sivaraam** [Originate/git-town#938] opened 2017-05-25 04:16 UTC
Following the [instructions](http://www.git-town.com/install.html) to install git-town on Debian, I searched for the `deb` packages in the releases. It seems that there aren't any for the releases other than version `1.0.0`. I guess the website must be updated. 

//Note// : I'm not sure where to report this and hence creating an issue in the repository.

**Comment by kevgo** [comment] 2017-05-25 15:02
Thanks for checking in about this. @allonsy is working on releasing upgraded version for 4.0. Any updates on when those will be available?

**Comment by charlierudolph** [comment] 2017-05-25 16:12
Closing this as duplicate of #924

**Closed by charlierudolph** 2017-05-25 16:12 UTC
