### ISSUE TITLE
On windows command line, colored output is not working

### ISSUE THREAD

**Issue by arekkas** [Originate/git-town#954] opened 2017-06-01 07:55 UTC
![image](https://cloud.githubusercontent.com/assets/3372410/26670059/7c75bdca-46b0-11e7-9f10-7a48b62c0d23.png)

**Comment by kevgo** [comment] 2017-06-01 14:08
Looks like https://github.com/fatih/color requires a different way of using it on Windows:

```go
// Windows supported too! Just don't forget to change the output to color.Output
fmt.Fprintf(color.Output, "Windows support: %s", color.GreenString("PASS"))

**Comment by charlierudolph** [comment] 2017-09-01 19:37
This appears to have been closed accidentally when #1018 was merged. Reopening...

**Comment by kevgo** [comment] 2017-09-06 03:58
@arekkas cannot reproduce on Windows 7. Colors work in the latest release, in Git Bash, Git CMD, as well as the standard CMD. See attached screenshot of the standard CMD with proper colors.

![image](https://user-images.githubusercontent.com/268934/30093833-e31a7396-927c-11e7-89f2-052f6f876411.png)

**Comment by kevgo** [comment] 2017-09-06 03:59
Closing for now as "can't replicate", please reopen if the issue persists.

**Comment by kevgo** [comment] 2017-09-06 04:29
Found an area where colors still don't work: during setup of branches. Steps to reproduce:
- checkout a new branch with unknown parent
- run `git sync`

![image](https://user-images.githubusercontent.com/268934/30094443-3d2b0f36-9281-11e7-9326-81b314cfb47f.png)

**Closed** 2017-09-30 03:56 UTC
