### ISSUE TITLE
`git-town hack` broken on windows

### ISSUE THREAD

**Issue by arekkas** [Originate/git-town#955] opened 2017-06-01 08:07 UTC
```
git-town hack fix-welcome

[master] git fetch --prune

cd C:/workspace/js/sites-app

[master] git rebase origin/master
Current branch master is up to date.

[master] git checkout -b fix-welcome master
Switched to a new branch 'fix-welcome'

[fix-welcome] git push -u origin fix-welcome
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/ory/sites-app.git
 * [new branch]      fix-welcome -> fix-welcome
Branch fix-welcome set up to track remote branch fix-welcome from origin.

cd C:\workspace\js\sites-app
2017/06/01 10:06:32 open /tmp/hack_C:_workspace_js_sites-app: The system cannot find the path specif
ied.
```

**Comment by kevgo** [comment] 2017-06-01 11:36
This should be fixed by https://github.com/Originate/git-town/commit/ac68293714e2257629c1e6d6812bfe8e442145b7, which will be released later today via https://github.com/Originate/git-town/pull/953.

**Comment by charlierudolph** [comment] 2017-06-01 15:39
closing as a duplicate of #925

**Closed by charlierudolph** 2017-06-01 15:39 UTC

**Comment by charlierudolph** [comment] 2017-06-01 15:50
4.1.0 released with a fix

**Comment by arekkas** [comment] 2017-06-04 13:47
Not working, probably because `/tmp` isn't a directory on windows...

```
cd C:\workspace\go\src\github.com\ory\fosite
2017/06/04 15:46:41 open /tmp/hack_C--workspace-go-src-github-com-ory-fosite: The system cannot find the path specified.
```

**Comment by kevgo** [comment] 2017-06-05 08:06
We should use [os.TempDir](https://golang.org/pkg/os/#TempDir) to determine the root temp directory to use.
